DROP SCHEMA IF EXISTS beach CASCADE;

CREATE SCHEMA beach;

-- 10.5.
CREATE TABLE IF NOT EXISTS beach.customers (
    customer_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text,
    last_name text,
    email text,
    phone text,
    created_at date
);

-- 10.6.
CREATE TABLE IF NOT EXISTS beach.equipment (
    equipment_id bigserial PRIMARY KEY,
    type text,
    decscription text,
    replacement_cost numeric(7, 2),
    missing boolean
);

-- 10.7.
CREATE TABLE IF NOT EXISTS beach.rentals (
    customer_id int REFERENCES beach.customers (customer_id),
    equipment_id int REFERENCES beach.equipment (equipment_id),
    rental_date date NOT NULL,
    return_date date,
    PRIMARY KEY (customer_id, equipment_id, rental_date)
);

