DROP SCHEMA IF EXISTS beach CASCADE;

CREATE SCHEMA beach;

-- 10.5.
CREATE TABLE IF NOT EXISTS beach.customers (
    customer_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text UNIQUE,
    phone text UNIQUE,
    created_at date NOT NULL DEFAULT CURRENT_DATE,
    CHECK (email IS NOT NULL OR phone IS NOT NULL)
);

-- 10.6.
CREATE TABLE IF NOT EXISTS beach.equipment (
    equipment_id bigserial PRIMARY KEY,
    type text NOT NULL,
    decscription text,
    replacement_cost numeric(7, 2) CHECK (replacement_cost IS NULL OR replacement_cost > 0),
    missing boolean NOT NULL DEFAULT FALSE
);

-- 10.7.
CREATE TABLE IF NOT EXISTS beach.rentals (
    customer_id int REFERENCES beach.customers (customer_id) ON DELETE CASCADE,
    equipment_id int REFERENCES beach.equipment (equipment_id) ON DELETE CASCADE,
    rental_date date NOT NULL,
    return_date date,
    PRIMARY KEY (customer_id, equipment_id, rental_date)
);

